### ISSUE TITLE
[Feature Request] Sky should also be affected by fog

### ISSUE THREAD

**Issue by TSEG6** [JimiIT92/BetterPaleGarden#1]
**Is your feature request related to a problem? Please describe.**
It looks kinda weird with the fog not affecting the sky especially at night

**Describe the solution you'd like**
The fog should cover up the sky so that it blends in with the fog that can be seen on land
**Describe alternatives you've considered**
Could also be a client side option & it could only affect night times as well?

**Additional context**
![image](https://github.com/user-attachments/assets/38ac8e49-d0ac-434f-9479-ec09523ffe20)
this looks strange

**Comment by JimiIT92** [comment]
Yeah I know it feels odd, the point is that just by enabling the sky-fog, there are some other issues that arises that are also very weird to look at. But I'll definitively find a way to fix in a future update ;)

**Comment by JimiIT92** [comment]
Version 1.1 has been released. It contains some improvements to the Fog system, which sould also fix the rendering issue :) Let me know if there are any other issues :)

https://modrinth.com/mod/hendrixs-better-pale-garden/version/1.1.0-Fabric
